travis:
  secure:
    BINSTAR_TOKEN: CzY6Apul7VR2+4Eyna2t5WNZ7GkvNynkRKsaShMFwRJlUFWhakNHdVvHUd2LIVwDsUVhuSx1V4fO7NRxOpYk6YEOR0Jt4c8EbJQzLVN3BZP/EaphhPtrKByTnx9fuOu3JfVgo05mCOTMUzgq12WCUunTuDSiyM7ezb83SrrV8UlKzk2orizMci82Eo6Z8bU062jsbN8FioBEYrUfB+zWo7AW1e9uoTinWJjgEdsa+QY8eLCVj3yT//Bu5Edj0i/yqExcJOfLPRHzK6bZn9J5PYSEJCd8BuYHOKbxNgm1kXz7+5cKliedzcZV1MalHMxSBJjAulBbGIMfNZu6z4OMHH/AtpYO9F+9ShDLxwAi+xigN0HHS7a+tXlxkc3nX80CWh/rPBdE99CvPsXa4v35lNqRidoE1vBQa3lNILBgUkvjuDZ5go67b5PhFyDoJA/ijEIA66nQ8xBBdRwZETBCieufFpvIDQi5KMylNDztK37/fF3RyPIlByM0N3wB/bPZ7wccyQJRrwpZHBuMNSmT8QkExRbLF4MIwKZhGPnAujpNFscM8r+WmT2EVz46sRafSj3zo/tR58BH977DSpMHhOcdKF1rBlvpmSQMtdgwwgnGSk52oMU2OoFQm9/yhWLuARUS2Q5YcSZBw3w9GrrT2IIqChn22HbPHrdrNN57Hgs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
