travis:
  secure:
    BINSTAR_TOKEN: FRRmH9BV+L8p5BUkGYkMVeXPCGP4XxSmZMpiSO2gHUpwdIX6lyZlYSyTa8dewwC1UzQHjp/IUNRiJzBbasLq46gV9XkBo9+x+Xmx/fBVDbQKuWPCU0sMOEOtWRfYdlFUGB75fas2w/eqU/LsJgB+Byx9beD92aVF50FRy7eMnZU1igRwwunuJDIT+thgsCLRNOj5tl5qJxgxC/jcgul+208tUDlK24CkRQuDgNKu/P+xvE2AtLHjvMteZaylcPNN/Rorjfex8fWMXxeo7zlm+6PIoojJOKYTkcu37GV/ym4sHmK17y3yAW3ubI6IocbY45GM46uUIdqXtKAXBURF7fd03jY4i5Aj6JjCqdON0Cwcl8rAB/ghW/dZjQy/9uKIY3z0+mljoQ3kU5wfUeCx/SILvo+aG6mmvF2rVUwq7btbYYBMOtIwEyKGLYjwf4Rtw8l7PosaraLxP0XJ9tPmYrMAd+eENq14+jhJIRxGeUDEJ3ejboxiKVPswU2ATn/Q37LKBcNbasKKrUxzORbm1EpknNhS4avRcnLXXpYEQ76R/SEYDUx7G24YRhSNAg/HKMSF+uC6DIzgvPh1oJcEx/J7WDneNzn9ArtpiQLkTmcbqHuLSkWcKjoVaVnkCNe7RGoDCfMv7FEPSBTCIbckq30JaoHZYUV71AMvc+HebZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
